Import("env")

public_headers_list="""
    #libs/ixp_osal/include
    #libs/ixp_osal/include/modules
    #libs/ixp_osal/include/modules/bufferMgt
    #libs/ixp_osal/include/modules/ioMem
    #libs/ixp_osal/include/platforms
    #libs/ixp_osal/include/platforms/ixp400
    #libs/ixp_osal/os/l4aos/include
    #libs/ixp_osal/os/l4aos/include/ixp400
"""


srclist = """
    os/l4aos/src/IxOsalOsCacheMMU.c
    os/l4aos/src/IxOsalOsMsgQ.c
    os/l4aos/src/IxOsalOsSemaphore.c
    os/l4aos/src/IxOsalOsServices.c
    os/l4aos/src/IxOsalOsThread.c
    os/l4aos/src/ixp400/IxOsalOsIxp400.c
    os/l4aos/src/ixp400/IxOsalOsSemaphoreAsm.S
    src/core/IxOsalTime.c
    src/modules/bufferMgt/IxOsalBufferMgt.c
    src/modules/ioMem/IxOsalIoMem.c
    src/platforms/ixp400/IxOsalIxp400.c
"""

liblist = "c l4"

cpppath    = env["CPPPATH"]    + ["#sos", "#libs/lwip/include"]
cppdefines = env["CPPDEFINES"] + ["l4aos"]

lib = env.KengeLibrary("ixp_osal",
		       source = Split(srclist),
		       public_headers = Split(public_headers_list),
		       LIBS = Split(liblist),
		       CPPDEFINES = cppdefines,
		       CPPPATH = cpppath)

Return("lib")

# vim: filetype=python
